### ISSUE TITLE
Make `stack test --pedantic` work

### ISSUE THREAD

**Issue by Minoru** [Minoru/hakyll-convert#52]
Commit c012802bbc999d47e1e46b85b83df6f41098646b fails to compile with Stackage LTS 21.6 (GHC 9.4.5):

```
% stack test --pedantic
hakyll-convert> build (lib + exe + test)
Preprocessing library for hakyll-convert-0.3.0.4..
Building library for hakyll-convert-0.3.0.4..
Preprocessing test suite 'golden' for hakyll-convert-0.3.0.4..
Building test suite 'golden' for hakyll-convert-0.3.0.4..
[1 of 6] Compiling Golden.GoldenTestHelpers

/home/minoru/src/hakyll-convert/test/golden/Golden/GoldenTestHelpers.hs:14:1: error: [-Worphans, -Werror=orphans]
    Orphan instance: instance Show DistilledPost
    Suggested fix:
      Move the instance declaration to the module of the class or of the type, or
      wrap the type with a newtype and declare the instance on the new type.
   |
14 | deriving instance Show DistilledPost
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Progress 1/2

--  While building package hakyll-convert-0.3.0.4 (scroll up to its section to see the error) using:
      /home/minoru/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.8.1.0_ghc-9.4.5 --verbose=1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.8.1.0 build lib:hakyll-convert exe:hakyll-convert test:golden test:spec --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```
